config/routes.rb
Rails.application.routes.draw do
root 'artists#index'
resources :artists, only: [:index, :show]
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @album = @artist.albums.all
  end

  protected
    def artist_params
      params.require(:artist).permit(:name, :image_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">
	<h1>Artistas</h1>
	<div class="row">
	  <%  @artists.each do |artist| %>
	  <div class="col-sm-6 col-md-3">
	  	<div class="thumbnail">
	  	  <img src="<%= artist.image_url %>" alt="<%= artist.name %>">
	  	    <div class="caption">
	  	      <h3><%= artist.name %></h3>
	  	      <div>
	  	        <%= link_to "Ver mas", artist_path(artist), class: "btn btn-primary btn-lg btn-block" %>
	  	      </div>
	  	    </div>
	  	</div>
	  </div>
		<% end %>
	</div>
</div>

app/views/artists/show.html.erb
<div class="container">
	<h1><%= @artist.name %></h1>
	<h3> Albums (<%= @album.length %>)</h3>
	</br>

	<div class="row">
	  <div class="col-md-8">
		  <%  @album.each do |album| %>
		  <div class="col-sm-6 col-md-4">
			  <div class="thumbnail">
				  <img src="<%= album.image_url %>" alt="<%= album.name %>">
				  <div class="caption">
				  	<strong><%= album.name %></strong>
				  	  <p> <%= album.released_at %> </p>
				  </div>
			  </div>
		  </div>
			<% end %>
		</div>

		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
		  	<img src="<%= @artist.image_url %>" alt="<%= @artist.name %>">
		  </div>
		</div>
	 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clon Spotify</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <header>
  		<nav class="navbar navbar-inverse">
  			<div class="navbar-header">
      		<a class="navbar-brand" href="#">Clon Spotify</a>
    		</div>
    		<div class="collapse navbar-collapse navbar-ex1-collapse">
  				<ul class="nav navbar-nav navbar-left">
  					<li><%= link_to "Artistas", artists_path %></li>
  					<li><a href="#">Musica</a></li>
  				</ul>
  				<ul class="nav navbar-nav navbar-right">
  					<li><a href="#">Mi Cuenta</a></li>
  				</ul>
    		</div>
  		</nav>
  	</header>

    <%= yield %>

  </body>
</html>